### PR TITLE
added nSampl parameter that speeds up evaluating large csv

### PR DESCRIPTION
**Pull request by vykhand**
added nSampl parameter that speeds up evaluating large csv - it just reads nSample rows to evaluate schema

### CODE REVIEW

**Comment by seahboonsiew** [comment]
Looks good. Can you also update readme.md to reflect this change?

**Comment by vykhand** [comment]
Done, however I also added another change - counting "NA" as null. It is actually my first pull request on github so I am not sure how we separate these :) If you can't accept all at once, let me know, I'll try to fix it somehow

**Comment by seahboonsiew** [comment]
is there a way to set nsampl to evaluate all rows? sometimes we may not know the number of rows in advance

**Comment by vykhand** [comment]
Sorry that was a premature merge, please revert. There was a syntax error, I was in a hurry and could not fix it - was editing the file in github. Please revert the pull for now and I will let you know when I fix it.

**Pull request merged**
